server.port: 7002
server.error.include-message: always

logging:
  level:
    root: INFO
    '[se.com]': DEBUG

---

spring:
  config:
    activate:
      on-profile:
      - docker

server:
  port: 8080