server.port: 7002
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

logging:
  level:
    root: INFO
    '[com.micro.microservices]': DEBUG

spring.data.mongodb.auto-index-creation: true

---

spring:
  config:
    activate:
      on-profile:
      - docker

server:
  port: 8080

spring.data.mongodb.host: mongodb