spring:
    application:
        name: product-service

server.port: 7001

Logging:
    Level:
        root: INFO
        '[com.micro.microservices]': DEBUG

---

spring:
  config:
    activate:
      on-profile:
      - docker

server:
  port: 8080