spring:
    application:
        name: product-service

server.port: 7001

spring.data.mongodb:
    host: localhost
    port: 27017
    database: product-db

spring.data.mongodb.auto-index-creation: true

Logging:
    Level:
        root: INFO
        '[com.micro.microservices]': DEBUG

---

spring:
  config:
    activate:
      on-profile:
      - docker

server:
  port: 8080