server.port: 7003
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:postgresql://localhost/review-db
  username: robin
  password: batmobil

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    '[se.com]': DEBUG

---

spring:
  config:
    activate:
      on-profile:
      - docker

server:
  port: 8080

spring.datasource:
  url: jdbc:postgresql://postgres/review-db